# schemas.py
from pydantic import BaseModel, Field
from typing import Optional, List, Literal, Dict


class SafetyResult(BaseModel):
    status: Literal["ok", "review", "block"]
    reason: str


class QuizQuestion(BaseModel):
    """
    One question in the AI-generated quiz.
    """
    id: str = Field(
        description="Stable identifier for the question, e.g. 'q1', 'trigger', 'frequency'."
    )
    question: str = Field(
        description="The exact question text to show the user."
    )
    helper_text: Optional[str] = Field(
        default=None,
        description="Optional short hint or example to clarify the question."
    )


class QuizForm(BaseModel):
    """
    The complete quiz generated by the AI for a specific habit.
    """
    habit_name_guess: str = Field(
        description="Short guess of the habit name, based on the user's description."
    )
    questions: List[QuizQuestion] = Field(
        description="8–10 tailored questions for this user's habit."
    )


class QuizSummary(BaseModel):
    """
    Compressed representation of the user's habit profile,
    derived from original description + quiz + answers.
    """

    # Preserve exact wording
    user_habit_raw: str

    # Canonical but faithful name
    canonical_habit_name: str

    # Broad category + confidence
    habit_category: str
    category_confidence: Literal["low", "medium", "high"]

    # More specific type
    product_type: str

    # Behavioral pattern fields
    severity_level: Literal["mild", "moderate", "severe"]
    main_trigger: str
    peak_times: str
    common_locations: str
    emotional_patterns: str
    frequency_pattern: str
    previous_attempts: str
    motivation_reason: str
    risk_situations: str


class Plan21D(BaseModel):
    plan_summary: str
    day_tasks: Dict[str, str]


class SafetyResult(BaseModel):
    risk: Literal["none", "self_harm", "eating_disorder", "severe_addiction", "violence", "other"]
    action: Literal["allow", "block_and_escalate"]
    message: str



class QuizQuestion(BaseModel):
    """
    One question in the AI-generated quiz.
    """
    id: str = Field(
        description="Stable identifier for the question, e.g. 'q1', 'trigger', 'frequency'."
    )
    question: str = Field(
        description="The exact question text to show the user."
    )
    helper_text: Optional[str] = Field(
        default=None,
        description="Optional short hint or example to clarify the question."
    )


class QuizForm(BaseModel):
    """
    The complete quiz generated by the AI for a specific habit.
    """
    habit_name_guess: str = Field(
        description="Short guess of the habit name, based on the user's description."
    )
    questions: List[QuizQuestion] = Field(
        description="8–10 tailored questions for this user's habit."
    )


class QuizSummary(BaseModel):
    """
    Compressed representation of the user's habit profile,
    derived from original description + quiz + answers.
    """

    # Preserve exact wording
    user_habit_raw: str

    # Canonical but faithful name
    canonical_habit_name: str

    # Broad category + confidence
    habit_category: str
    category_confidence: Literal["low", "medium", "high"]

    # More specific type
    product_type: str

    # Behavioral pattern fields
    severity_level: Literal["mild", "moderate", "severe"]
    main_trigger: str
    peak_times: str
    common_locations: str
    emotional_patterns: str
    frequency_pattern: str
    previous_attempts: str
    motivation_reason: str
    risk_situations: str


class Plan21D(BaseModel):
    plan_summary: str
    day_tasks: Dict[str, str]


class HabitState(BaseModel):
    """
    Global state passed between LangGraph nodes.
    """

    # Identification / meta
    user_id: Optional[str] = None

    # Initial short description like: "I'm addicted to Zyn"
    habit_description: Optional[str] = None

    # AI-generated quiz
    quiz_form: Optional[QuizForm] = None

    # Raw quiz answers from frontend
    # You can store this as JSON string or formatted text like:
    # "q1: ..., q2: ..., q3: ..."
    user_quiz_answers: Optional[str] = None

    # LLM outputs
    safety: Optional[SafetyResult] = None
    quiz_summary: Optional[QuizSummary] = None
    plan21: Optional[Plan21D] = None

    # Coaching
    last_user_message: Optional[str] = None
    coach_reply: Optional[str] = None

    # Conversation history for the coach
    # Each message: {"role": "user" | "assistant", "content": "..."}
    chat_history: List[Dict[str, str]] = []

    # Optional routing field if you add routers later
    next: Optional[str] = None

    canonical_habit_name: Optional[str] = None
    canonical_confidence: Optional[str] = None


